In [1]:
import numpy as np

In [2]:
##activation function definition
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [3]:
###Function to generate random weights based on the number of input neurons and the output neurons.
def nn(inputs, neurons):
    W = np.random.randn(neurons, inputs)
    return(W)
## Function determine the output of a layer using the previous output and the weights.
 def feedforward(A_prev,W):
    Z = np.dot(W, A_prev)
    A = sigmoid(Z)
    return A

In [4]:

from random import seed
from random import random
# seed random number generator
seed(1)
  
# number of input neurons
i_count = int(input("Enter number of input neurons : "))

# iterating till the range
for i in range(0, i_count):
    
    inp = np.random.randn(i_count) # generate random input values for each input neuron
    
 
      
print(inp) #prints the input values

Enter number of input neurons : 2
[ 0.07100624 -0.24553117]


In [5]:
h_count = int(input("Enter number of hidden layers :"))
print(h_count)

Enter number of hidden layers :4
4


In [6]:
## creating an array h to hold the number neurons in each layer. For thhis initialise it with
##hidden layer count+2 number of zeros.
## input layer, h_count number of hidden layers and output layer constitute the 'h' array size.
h = np.zeros(h_count+2,int)
h[0] = i_count ### make the first element of 'h' array as the input layer neurons count.
for k in range(1,h_count+1):
    h[k] = int(input("Enter number of neurons in each hidden layer :"))
    

Enter number of neurons in each hidden layer :3
Enter number of neurons in each hidden layer :2
Enter number of neurons in each hidden layer :2
Enter number of neurons in each hidden layer :3


In [7]:
o_count = int(input("Enter number of output neurons :"))
h[h_count+1]= o_count ## stores the output layer neuron count to the last position of the array 'h'
print(o_count)

Enter number of output neurons :2
2


In [8]:
#array which contains the number of neuron in each layer
h

array([2, 3, 2, 2, 3, 2])

In [11]:
### initial value of A is the input.
A = inp
for i in range (0,h_count+1): ## iterates from input layer to the output layer
    W = nn(h[i],h[i+1]) ## random weight is generated based on the neurons on the present layer and the next layer
    print('\nWeight matrix at each layer\n',W)    
    print('dimension of weight matrix\t\t\t',np.shape(W))
    A = feedforward(A,W) ##function call to find the values of the output of each layer.
    print('each layer outputs :',A)


Weight matrix at each layer
 [[ 1.90060025  1.53887176]
 [ 0.12175743 -0.52789298]
 [ 1.16821872  0.31930448]]
dimension of weight matrix			 (3, 2)
each layer outputs : [0.43957514 0.53450997 0.5011379 ]

Weight matrix at each layer
 [[-0.66682492 -0.30968974  1.42971299]
 [ 1.36574517 -0.68776097  0.76913194]]
dimension of weight matrix			 (2, 3)
each layer outputs : [0.56410314 0.64980307]

Weight matrix at each layer
 [[-1.25955457  0.95219566]
 [-0.53700771  0.0262287 ]]
dimension of weight matrix			 (2, 2)
each layer outputs : [0.47707134 0.42901177]

Weight matrix at each layer
 [[-0.52769517 -0.06082763]
 [ 0.50959044  0.58263125]
 [-0.20546593  0.23606011]]
dimension of weight matrix			 (3, 2)
each layer outputs : [0.43098243 0.62082859 0.50081266]

Weight matrix at each layer
 [[ 0.16646039 -0.62152474 -0.26182602]
 [ 0.65957605  0.1209905   0.25409088]]
dimension of weight matrix			 (2, 3)
each layer outputs : [0.39049199 0.61931269]
